# yaml-language-server: $schema=./.kokimoki/schema.json

# Theme variables for DaisyUI
theme:
  colorBase100: 'oklch(100% 0 0)'
  colorBase200: 'oklch(97% 0 0)'
  colorBase300: 'oklch(92% 0 0)'
  colorBaseContent: 'oklch(20% 0 0)'
  colorPrimary: 'oklch(85% 0.199 91.936)'
  colorPrimaryContent: 'oklch(42% 0.095 57.708)'
  colorSecondary: 'oklch(75% 0.183 55.934)'
  colorSecondaryContent: 'oklch(40% 0.123 38.172)'
  colorAccent: 'oklch(0% 0 0)'
  colorAccentContent: 'oklch(100% 0 0)'
  colorNeutral: 'oklch(37% 0.01 67.558)'
  colorNeutralContent: 'oklch(92% 0.003 48.717)'
  colorInfo: 'oklch(74% 0.16 232.661)'
  colorInfoContent: 'oklch(39% 0.09 240.876)'
  colorSuccess: 'oklch(76% 0.177 163.223)'
  colorSuccessContent: 'oklch(37% 0.077 168.94)'
  colorWarning: 'oklch(82% 0.189 84.429)'
  colorWarningContent: 'oklch(41% 0.112 45.904)'
  colorError: 'oklch(70% 0.191 22.216)'
  colorErrorContent: 'oklch(39% 0.141 25.723)'
  radiusSelector: '1rem'
  radiusField: '0.5rem'
  radiusBox: '1rem'
  sizeSelector: '0.25rem'
  sizeField: '0.25rem'
  border: '1px'
  noise: '0'
  depth: '1'

# Translations
title: 'Host Starter'
welcomeMessageMd: |
  # Welcome!
  This is my awesome game.

lobbyConnectionsMd: |
  # Connections
  Lobby connections example.
players: 'Players'
sharedStateMd: |
  # Shared State
  Lobby shared state example.
timeElapsed: 'Time elapsed'
buttonPresses: 'Button presses'
incrementButton: 'Increment'
decrementButton: 'Decrement'

loading: 'Loading...'
or: 'OR'
share: 'Share:'
copy: 'Copy'
copied: 'Copied!'

hostGameTitle: 'Host new game'
hostButton: 'Host'
host: "You're the host"

joinGameTitle: 'Join existing game'
joinInputPlaceholder: 'Enter code...'
joinButton: 'Join'

connecting: 'Connecting to lobby...'

menuTitle: 'Menu'
menuWelcomeMessage: 'Welcome Message'
menuConnections: 'Connections'
menuSharedState: 'Shared State'
menuExitLobby: 'Exit Lobby'
