# yaml-language-server: $schema=./.kokimoki/schema.json

# Translations
title: 'Host Starter'

gameLobbyMd: |
  # Get ready

  Host is stating the game soon. Meanwhile, get familiar with the rules.

  ## Gameplay

  Each turn the team votes on one action to take. Actions can be attacking the enemy, defending the team or powering up for future turns.

  ## Rules

  1. Block resets to 0 after every turn.
  2. Strength increases attack effectiveness.
  3. Fortitude increases block effectiveness.
  4. At the start of the round the team heals for 5 health.

connectionsMd: |
  Scan the QR to join the game.

sharedStateMd: |
  # Shared State Host
  This is an example of shared state view. Host can start the game, open the presenter screen and allow players to join by scanning the QR.

  ## Host Actions
  Here's a demo of dashboard actions that can be used to control the state on presenter and player screens.

sharedStatePlayerMd: |
  # Shared State Player
  You are connected as a player. Host has started the game. In this shared state example the playtime is synchronized between all players.

players: 'Players Connected'
online: 'Online'
offline: 'Offline'
startButton: 'Start Game'
stopButton: 'Stop Game'

loading: 'Loading...'

menuHelpMd: |
  # Help

  This is the help section. Here you can find information about how to play the game and get assistance if needed.

  ## How to Play

  1. Join the game using the provided link or QR code.
  2. Follow the instructions on your screen.
  3. Interact with other players as required by the game.

  ## Getting Assistance

  If you encounter any issues, please contact the host or refer to the FAQ section on our website.

createProfileMd: |
  # Welcome!

  Please enter your name to join the game.

playerNamePlaceholder: 'Your name...'
playerNameLabel: 'Name:'
playerNameButton: 'Continue'

playerLinkLabel: 'Player Link'
presenterLinkLabel: 'Presenter Link'

togglePresenterQrButton: 'Toggle Presenter QR'
openPlayerHelpButton: 'Force Players Help to Open'

menuAriaLabel: 'Open menu drawer'
menuHelpAriaLabel: 'Open help drawer'

roundMd: |
  Get ready for battle!

turnMd: |
  # Your Turn!

  Vote with the team what action to take next.

victoryMd: |
  # Victory!

  Congratulations on defeating the enemy!

rewardMd: |
  # Reward

  Vote with the team to select your reward.

gameOverMd: |
  # Game over!

  If there was magic here, it's long gone now.
